CREATE TABLE OAUTH2_CLIENT_INFO
(
ID				BIGINT				PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
APP_NAME		VARCHAR(50)			NOT NULL UNIQUE,
CLIENT_ID		VARCHAR(200)		NOT NULL UNIQUE,
CLIENT_SECRET	VARCHAR(200)		NOT NULL UNIQUE,
REDIRECT_URL	VARCHAR(1000)		NOT NULL,
CREATE_DATE		TIMESTAMP			NOT NULL
);

INSERT INTO OAUTH2_CLIENT_INFO(APP_NAME, CLIENT_ID, CLIENT_SECRET, REDIRECT_URL, CREATE_DATE) VALUES 
('Jersey-API-Server-Example', 'abcaa9e0c61e7cccc4758520d752366f', '76199ba6a6c15c066cd153b24a9a9b29', 
'http://localhost:8080/JerseyExample/login/oltu/oauth2callback', TIMESTAMP('2015-12-01 15:57:46.827'));

CREATE TABLE OAUTH2_CLIENT_TOKEN
(
ID				BIGINT				PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CLIENT_INFO_ID	BIGINT				NOT NULL UNIQUE REFERENCES OAUTH2_CLIENT_INFO(ID),
OAUTH_CODE		VARCHAR(200)		NOT NULL,
OAUTH_TOKEN		VARCHAR(200)		NOT NULL,
UPDATE_DATE		TIMESTAMP			NOT NULL
);
